swagger: '2.0'
info:
  version: '0'
  title: TimeSlot API
  description: ''

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
 
consumes:
- application/json

produces: 
- application/json

paths:
  /appointments:
    get:
      operationId: getAppointments
      summary: Get appointments with filters
      parameters: 
        
        - in: query
          name: "day_of_week"
          type: string
          description: "The day of the week to get appointments from"
        
        - in: query
          name: "time_of_day"
          type: string
          description: "The time requested"
        
        - in: query
          name: "dentist_name"
          type: "string"
          description: "The dentist requested"
  
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - "appointments"
              - "links"
            properties:
              appointments:
                $ref: "#/definitions/Appointments"
              links:
                $ref: "#/definitions/links"
        400:
          description: Error
          schema:
            type: string
            example: "Unable to parse query string"
        403:
          description: Error
          schema: 
            type: string
            example: "Not Found"
            
    post:
      operationId: makeAppointment
      summary: "Make a new appointment"
      parameters:
        
        - name: "appt_info"
          in: body
          schema:
            $ref: '#/definitions/Appointment'
            
      responses:
        201:
          description: "Appointment made successfully!"
          schema:
            type: object
            required:
              - "appointment"
              - "links"
            properties:
              appointment:
                $ref: "#/definitions/Appointment"
              links:
                $ref: "#/definitions/links"
        400:
          description: Error
          schema:
            type: string
            example: "Unable to create appointment"
        404:
          description: "No such timeslot available"
      
  /appointments/cancel:          
    post: # Amending an appointment
      operationId: cancelAppointment
      summary: "Cancel Appointment"
      parameters:
        - name: "appt_info"
          in: body
          required: true
          schema:
            $ref: '#/definitions/Appointment'

      responses:
        202:
          description: "Appointment canceled"
          schema:
            type: object
            required:
              - "links"
            properties:
              links:
                $ref: "#/definitions/links"
        400:
          description: Error
          schema:
            type: string
            example: "Unable to delete appointment"
        404:
          description: "No such appointment at this time"
          
definitions:
  Appointment:
    type: "object"
    properties: 
      time_of_day: 
        type: "string"
      day_of_week: 
        type: "string"
      dentist_name: 
        type: "string"
      patient_name:
        type: "string"
      status:
        type: boolean
        
  Appointments: # for getting all appointments of one day 
    type: array
    items:
      $ref: '#/definitions/Appointment'
  
  link:
    type: object
    properties:
      description:
        type: "string"
      href:
        type: "string"
      rel:
        type: "string"
      request:
        type: "string"
    example:
      - href: "https://localhost:8000/appointments"
        rel: "next"
        request: "POST"
        description: "book an appointment"
  
  links:
    type: array
    items:
     $ref: '#/definitions/link'
    
    example:
      - href: "https://localhost:8000/appointments"
        rel: "next"
        request: "POST"
        description: "book an appointment"
        
      - href: "https://localhost:8000/appointments/cancel"
        rel: "next"
        request: "POST"
        description: "cancel an appointment"
      
# Added by API Auto Mocking Plugin
basePath: /timeslot_api

